name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: publish-esphome.yml
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: localbytes-plug-pm.yaml,minimal.yaml
      # CHANGEME: Set the name of your project here:
      name: Local Bytes Power Monitor Smart Plug
